name:                              Compilation and Testing Suite

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
      - docs/
jobs:

## Check Stage
  check-test-build:
    name:                          Check, test and build
    runs-on:                       ubuntu-latest
    steps:
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v2
        with:
          fetch-depth:             5
          submodules:              true
      - name:                      Install rust nightly
        uses:                      actions-rs/toolchain@v1
        with:
          target:                  wasm32-unknown-unknown
          override:                false
          components:              rustfmt, clippy
      - name:                      Checking rust
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --all  --verbose

## Test Stage
      - name:                      Testing rust
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          args:                    --all  --verbose

## Linting Stage
      - name:                      Clippy
        uses:                      actions-rs/cargo@master
        with:
          command:                 clippy
          args:                    --all-targets -- -D warnings

## Check Node Benchmarks
      - name:                      Check evercity-node
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          args:                    --verbose

## Build Stage
      - name:                      Building rust
        uses:                      actions-rs/cargo@master
        if:                        github.ref == 'refs/heads/master'
        with:
          command:                 build
          args:                    --all --release --verbose
      - name:                      Prepare artifacts
        if:                        github.ref == 'refs/heads/master'
        run:                       |
          mkdir -p ./artifacts;
          mv -v $CARGO_TARGET_DIR/release/evercity-node ./artifacts/;
        shell:                     bash
      - name:                      Upload artifacts
        if:                        github.ref == 'refs/heads/master'
        uses:                      actions/upload-artifact@v1
        with:
          name:                    evercity-substrate.zip
          path:                    artifacts/
